export const CITIES = [
  { value: "tehran", label: "تهران" },
  { value: "mashhad", label: "مشهد" },
  { value: "tabriz", label: "تبریز" },
  { value: "isfahan", label: "اصفهان" },
  { value: "shiraz", label: "شیراز" },
  { value: "karaj", label: "کرج" },
  { value: "ahvaz", label: "اهواز" },
  { value: "qom", label: "قم" },
  { value: "rasht", label: "رشت" },
  { value: "kermanshah", label: "کرمانشاه" },
  { value: "urmia", label: "ارومیه" },
  { value: "yazd", label: "یزد" },
  { value: "kerman", label: "کرمان" },
  { value: "zahedan", label: "زاهدان" },
  { value: "hamedan", label: "همدان" },
  { value: "arak", label: "اراک" },
  { value: "bandar_abbas", label: "بندرعباس" },
] as const;
